### ISSUE TITLE
Stuck waiting for docker

### ISSUE THREAD

**Issue by philiptolk** [willyguggenheim/kubify#1]
TASK [Waiting for Docker to configure] *********************************************************************************************************
task path: /Users/name/kubify/tools/kubify/kubify/k8s/ansible/install_osx.yaml:135

usr/local/bin/docker ps
Error response from daemon: dial unix docker.raw.sock: connect: connection refused

**Comment by willyguggenheim** [comment]
I'm on it!
This v0.3.x is a breaking change (large migration to allow M1 to work and to make Kubify 10x faster on Kind)
You might need to click the docker desktop hard reset button before upgrading
I will try to reproduce this edge case and will perfect the upgrade pattern
Thank you for your testing bro !!

**Comment by willyguggenheim** [comment]
fixed!
