### ISSUE TITLE
install stuck M1

### ISSUE THREAD

**Issue by philiptolk** [willyguggenheim/kubify#11]
TASK [Installing Homebrew] *************************************************************************************************************************************************************************************************************************************************************************************************
task path: /Users/diamond/Desktop/code/kubify/src/kubify/k8s/ansible/install_kubify_on_mac_osx_m1_m1x.yaml:65
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: diamond
<127.0.0.1> EXEC /bin/sh -c 'echo ~diamond && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/diamond/.ansible/tmp `"&& mkdir "` echo /Users/diamond/.ansible/tmp/ansible-tmp-1642205394.827517-51238-19071727981018 `" && echo ansible-tmp-1642205394.827517-51238-19071727981018="` echo /Users/diamond/.ansible/tmp/ansible-tmp-1642205394.827517-51238-19071727981018 `" ) && sleep 0'
Using module file /opt/homebrew/Cellar/ansible/5.0.1/libexec/lib/python3.10/site-packages/ansible/modules/command.py
<127.0.0.1> PUT /Users/diamond/.ansible/tmp/ansible-local-51178sui_x8f0/tmpss644_1z TO /Users/diamond/.ansible/tmp/ansible-tmp-1642205394.827517-51238-19071727981018/AnsiballZ_command.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /Users/diamond/.ansible/tmp/ansible-tmp-1642205394.827517-51238-19071727981018/ /Users/diamond/.ansible/tmp/ansible-tmp-1642205394.827517-51238-19071727981018/AnsiballZ_command.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/opt/homebrew/bin/python3.9 /Users/diamond/.ansible/tmp/ansible-tmp-1642205394.827517-51238-19071727981018/AnsiballZ_command.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /Users/diamond/.ansible/tmp/ansible-tmp-1642205394.827517-51238-19071727981018/ > /dev/null 2>&1 && sleep 0'
fatal: [127.0.0.1]: FAILED! => {
    "changed": true,
    "cmd": [
        "/usr/bin/ruby",
        "-e",
        "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    ],
    "delta": "0:00:00.054811",
    "end": "2022-01-14 16:09:55.030239",
    "invocation": {
        "module_args": {
            "_raw_params": "/usr/bin/ruby -e \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)\"",
            "_uses_shell": false,
            "argv": null,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true,
            "warn": false
        }
    },
    "rc": 1,
    "start": "2022-01-14 16:09:54.975428"
}

STDERR:

-e:1: `$(' is not allowed as a global variable name

MSG:

non-zero return code

PLAY RECAP *****************************************************************************************************************************************************************************************************************************************************************************************************************
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   

diamond@Golds-Mac-mini kubify %

**Comment by willyguggenheim** [comment]
Fixed! Thanks for the pairing sesh!

**Comment by willyguggenheim** [comment]
Also thank you for the detailed demo of this issue, super helpful!
