### ISSUE TITLE
make cloud tfsec issues

### ISSUE THREAD

**Issue by philiptolk** [willyguggenheim/kubify#18]
# But Why?
make cloud
 results
  ──────────────────────────────────────────
  passed               79
  ignored              0
  critical             5
  high                 3
  medium               4
  low                  4

  79 passed, 16 potential problem(s) detected.
# Priority ?

**Comment by willyguggenheim** [comment]
Will do

**Comment by willyguggenheim** [comment]
Marked with TODO
