### ISSUE TITLE
make cloud

### ISSUE THREAD

**Issue by philiptolk** [willyguggenheim/kubify#19]
# But Why?
make cloud
python3 -m kubify.cloud.deploy_local_clusters && \
                echo $CICD_ENABLE_CLOUDS_DEPLOY | grep 1 2>/dev/null && python3 -m kubify.cloud.deploy_clouds_clusters
make: *** [cloud] Error 1
# Priority ?

**Comment by willyguggenheim** [comment]
https://github.com/willyguggenheim/kubify/pull/21
