### ISSUE TITLE
Stuck on docker hard_reset_docker_mac

### ISSUE THREAD

**Issue by philiptolk** [willyguggenheim/kubify#2]
./kubify hard_reset_docker_mac
+ docker info
+ echo -n .
.+ sleep 1
+ docker info
+ echo -n .
.+ sleep 1
+ docker info
+ echo -n .

**Comment by willyguggenheim** [comment]
oh yeah, that function is no not finished .. but easy, will fix it 
thank you for the testing bro !!
happy Friday :)

**Comment by willyguggenheim** [comment]
fixed
