### ISSUE TITLE
separate cloud providers

### ISSUE THREAD

**Issue by philiptolk** [willyguggenheim/kubify#23]
# But Why?
I separated in branch 

https://github.com/willyguggenheim/kubify/blob/ed528a4c1f3784c55c8a4c5950b20a89f11e600d/Makefile#L105

to show that we should be able to use kubify with only one cloud provider or two or all three

Need to refactor terraform to modularize cloud providers
# Priority ?

**Comment by willyguggenheim** [comment]
Thank you for making example branch, yes, I am on it bro

**Comment by willyguggenheim** [comment]
Done and pushed
