### ISSUE TITLE
make format error

### ISSUE THREAD

**Issue by philiptolk** [willyguggenheim/kubify#93]
make format
conda env update --file environment.yml --prune
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - libzlib==1.2.12=h03a7124_4
  - libmambapy==0.27.0=py310h5fdb59d_0
  - ca-certificates==2022.9.24=h4653dfc_0
  - libarchive==3.5.2=h69ec738_3
  - libedit==3.1.20191231=hc8eb9b7_2
  - libcxx==14.0.6=h2692d47_0
  - krb5==1.19.3=hf9b2bbe_0
  - ruamel_yaml==0.15.80=py310h02f21da_1007
  - libiconv==1.17=he4db4b2_0
  - astroid==2.12.10=py310hbe9552e_0
  - brotlipy==0.7.0=py310hf8d0d8f_1004
  - pycosat==0.6.3=py310hf8d0d8f_1010
  - bzip2==1.0.8=h3422bc3_4
  - conda-package-handling==1.9.0=py310h8e9501a_0
  - libffi==3.4.2=h3422bc3_5
  - lazy-object-proxy==1.7.1=py310hf8d0d8f_1
  - libnghttp2==1.47.0=h232270b_1
  - icu==70.1=h6b3803e_0
  - conda==22.9.0=py310hbe9552e_1
  - libssh2==1.10.0=hb80f160_3
  - lz4-c==1.9.3=hbdafb3b_1
  - importlib-metadata==4.11.4=py310hbe9552e_0
  - libcurl==7.85.0=hd538317_0
  - libsqlite==3.39.4=h76d750c_0
  - tk==8.6.12=he1e0b03_0
  - reproc==14.2.3=h3422bc3_0
  - python==3.10.6=hbce4517_0_cpython
  - ncurses==6.3=h07bb92c_1
  - libmamba==0.27.0=h0745fb2_0
  - mamba==0.27.0=py310h25b57eb_0
  - xz==5.2.6=h57fd34a_0
  - libev==4.33=h642e427_1
  - lzo==2.10=h642e427_1000
  - reproc-cpp==14.2.3=hbdafb3b_0
  - wrapt==1.14.1=py310h02f21da_0
  - libxml2==2.10.2=ha9542bf_1
  - libsolv==0.7.22=h1280f1d_0
  - readline==8.1.2=h46ed386_0
  - cryptography==38.0.1=py310h4fe9c50_0
  - cffi==1.15.1=py310he00a5c5_0
  - pep517==0.12.0=py310hbe9552e_2
  - yaml==0.2.5=h3422bc3_2
  - zstd==1.5.2=h8128057_4
  - c-ares==1.18.1=h3422bc3_0
  - openssl==1.1.1q=ha287fd2_0
  - yaml-cpp==0.7.0=hb7217d7_2

make: *** [Makefile:61: format] Error 1

**Comment by willyguggenheim** [comment]
solved
